version: '3.8'

services:

  application:
    build: ./application
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: app
      DB_USERNAME: mysql
      DB_PASSWORD: mypass
      XDEBUG_SESSION: xdebug-docker
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
      EMAIL_HOST: mailhog
      EMAIL_USERNAME: ''
      EMAIL_PASSWORD: ''
      EMAIL_PORT: 1025
      EMAIL_FROM: notify@jobsmapp.com
      DOCKER: 1
    volumes:
      - ./application:/var/www/html

  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - "8081:8080"
    depends_on:
      - db

  flyway:
    image: flyway/flyway:8.5.4
    command: -url=jdbc:mysql://db -schemas=app -user=mysql -password=mypass -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    environment:
      SWAGGER_JSON: /tmp/openapi.json
    volumes:
      - ./application/docs/openapi.json:/tmp/openapi.json

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"