apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: application
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: application
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: application
    spec:
      containers:
        - env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_DATABASE
              value: app
            - name: DB_HOST
              value: db
            - name: DB_PASSWORD
              value: mypass
            - name: DB_USERNAME
              value: mysql
            - name: EMAIL_FROM
              value: notify@jobsmapp.com
            - name: EMAIL_HOST
              value: mailhog
            - name: EMAIL_PASSWORD
            - name: EMAIL_PORT
              value: "1025"
            - name: EMAIL_USERNAME
            - name: PHP_IDE_CONFIG
              value: serverName=xdebug-docker
            - name: QUEUE_EXCHANGE
              value: router
            - name: QUEUE_HOST
              value: rabbitmq
            - name: QUEUE_NAME
              value: notify
            - name: QUEUE_PASSWORD
              value: mypassword
            - name: QUEUE_PORT
              value: "5672"
            - name: QUEUE_USER
              value: myuser
          image: application
          name: application
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: application-claim0
      restartPolicy: Always
      volumes:
        - name: application-claim0
          persistentVolumeClaim:
            claimName: application-claim0
status: {}
